version: '3.7'

services:
  sales_helper:
    container_name: sales_helper
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - "sales_helper/:/app"
    ports:
      - 5173:5173


volumes:
  sales_helper: {}